      - name: Deploy on EC2
        run: |
          ssh -i ~/.ssh/cloudpulse_key ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            sudo chown -R ubuntu:ubuntu /home/ubuntu/cloudpulse-devops-platform
            git config --global --add safe.directory /home/ubuntu/cloudpulse-devops-platform
            cd /home/ubuntu/cloudpulse-devops-platform
            git pull origin main
            docker rm -f cloudpulse-container || true
            docker build --no-cache -t cloudpulse-app .
            docker run -d --name cloudpulse-container -p 80:5000 cloudpulse-app
          EOF
